# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

#===============================
# COMPLETIONS
#

source ~/.completion

source ~/.bashprompt

#===============================
# FREQUENTLY USED

az login